-- Oracle Autonomous Database-compatible schema for forecast inference logging.

create table inference_entities (
    entity_id varchar2(128) primary key,
    entity_type varchar2(64) default 'time_series' not null,
    display_name varchar2(256),
    metadata clob check (metadata is json),
    created_at timestamp with time zone default systimestamp not null,
    updated_at timestamp with time zone default systimestamp not null
);

create table inference_runs (
    run_id varchar2(64) primary key,
    entity_id varchar2(128) not null,
    status varchar2(32) not null,
    model_name varchar2(256),
    model_source varchar2(512),
    model_version varchar2(128),
    risk_band varchar2(32),
    confidence number,
    request_payload clob check (request_payload is json),
    ml_output clob check (ml_output is json),
    llm_output clob check (llm_output is json),
    error_message varchar2(2000),
    created_at timestamp with time zone default systimestamp not null,
    constraint fk_inference_runs_entity
        foreign key (entity_id) references inference_entities(entity_id)
);

create table forecast_points (
    point_id number generated by default as identity primary key,
    run_id varchar2(64) not null,
    forecast_step number not null,
    forecast_timestamp timestamp with time zone,
    median_value number,
    lower_value number,
    upper_value number,
    quantiles clob check (quantiles is json),
    created_at timestamp with time zone default systimestamp not null,
    constraint fk_forecast_points_run
        foreign key (run_id) references inference_runs(run_id)
);

create table driver_contributions (
    driver_id number generated by default as identity primary key,
    run_id varchar2(64) not null,
    driver_name varchar2(128) not null,
    contribution number,
    direction varchar2(64),
    description varchar2(1000),
    created_at timestamp with time zone default systimestamp not null,
    constraint fk_driver_contributions_run
        foreign key (run_id) references inference_runs(run_id)
);

create table llm_recommendations (
    recommendation_id number generated by default as identity primary key,
    run_id varchar2(64) not null,
    recommendation_text varchar2(2000) not null,
    rank_order number default 1 not null,
    created_at timestamp with time zone default systimestamp not null,
    constraint fk_llm_recommendations_run
        foreign key (run_id) references inference_runs(run_id)
);

create or replace view latest_successful_inference_v as
select *
from (
    select
        r.*,
        row_number() over (
            partition by r.entity_id
            order by r.created_at desc
        ) as rn
    from inference_runs r
    where r.status = 'completed'
)
where rn = 1;

